export enum EventType {
  Signup = 'Signup',
  Signin = 'Signin',
  Update = 'Update',
  Contact = 'Contact',
  SetWithdrawAddress = 'SetWithdrawAddress',
  Withdraw = 'Withdraw',
  CreateInvitationCode = 'CreateInvitationCode',
  SetCommission = 'SetCommission',
  SetTransferTargetUser = 'SetTransferTargetUser',
  Transfer = 'Transfer',
  WithdrawalRequest = 'WithdrawalRequest',
  WithdrawalCompleted = 'WithdrawalCompleted',
  DepositReceived = 'DepositReceived',
  KYCApproved = 'KYCApproved',
  KYCRejected = 'KYCRejected',
  Purchase = 'Purchase',
  AffiliatePurchase = 'AffiliatePurchase',
  AffiliateSignup = 'AffiliateSignup',
  GoodBenefit1 = ' GoodBenefit1',
  NewLogin = 'NewLogin',
  UpdatePassword = 'UpdatePassword',
  UpdateEmail = 'UpdateEmail',
  UpdateMobile = 'UpdateMobile',
  UpdateGoogleAuth = 'UpdateGoogleAuth',
  OrderCompleted = 'OrderCompleted',
  Announcement = 'Announcement',
  ProductPage = 'ProductPage'
}

export const EventTypes = Object.values(EventType)
